# Generated by Django 5.2.5 on 2025-08-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_number', models.IntegerField(help_text='Enter 6 digit roll number')),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(help_text='Required. Inform a valid email address.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Input Form',
                'verbose_name_plural': 'Input Forms',
            },
        ),
    ]
